[package]
name = "bevy-test"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_asset",
    "bevy_sprite",
] }
bevy_ecs_tilemap = "0.15.0"
bevy_pancam = "0.17.0"
rand = "0.9.0"

[features]
default = ["render"]
atlas = []
render = []
